export const COMPANY = {
  name: "Lynaris",
  legalForm: process.env["COMPANY_LEGAL_FORM"] ?? "Micro-entreprise",
  siret: process.env["COMPANY_SIRET"] ?? "En cours d'immatriculation",
  address: process.env["COMPANY_ADDRESS"] ?? "France",
  representative: process.env["COMPANY_REPRESENTATIVE"] ?? "Yoann Cabon",
  email: "contact@lynarisai.com",
  emailContact: "contact@lynarisai.com",
  emailSupport: "support@lynarisai.com",
  emailPresse: "presse@lynarisai.com",
  emailJobs: "jobs@lynarisai.com",
  phone: process.env["COMPANY_PHONE"] ?? "",
  hostingProvider: "Vercel Inc., 340 S Lemon Ave #4133, Walnut, CA 91789, USA",
  dataHostingProvider: "Supabase (Frankfurt, EU) via Vercel (CDN mondial)",
  dpo: "dpo@lynarisai.com",
  subprocessors: [
    { name: "Supabase", purpose: "Base de données et authentification", region: "EU (Frankfurt)", dpa: true },
    { name: "Vercel", purpose: "Hébergement et CDN", region: "EU + US", dpa: true },
    { name: "Anthropic", purpose: "Modèle de langage (agents IA)", region: "US", dpa: true },
    { name: "ElevenLabs", purpose: "Synthèse vocale (TTS)", region: "US", dpa: true },
    { name: "Deepgram", purpose: "Transcription vocale (STT)", region: "US", dpa: true },
    { name: "Twilio", purpose: "Téléphonie, SMS, voix", region: "US (données FR conformes RGPD)", dpa: true },
    { name: "Stripe", purpose: "Paiement et facturation", region: "EU", dpa: true },
    { name: "Resend", purpose: "Emails transactionnels", region: "US", dpa: true },
    { name: "Sentry", purpose: "Monitoring d'erreurs", region: "EU", dpa: true },
  ],
  retentionPolicies: {
    logs: "30 jours",
    clientData: "Durée du contrat + 30 jours",
    billing: "10 ans (obligation légale)",
    voiceTranscripts: "90 jours après l'appel",
  },
} as const
